baseURL = "https://garisfajarnusantaraabadi.com"
languageCode = "en-us"
paginate = 5
theme = "portio"
title = "PT Garis Fajar Nusantara Abadi"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Beranda"
url = "#home"
weight = 1
[[menu.main]]
name = "Tentang"
url = "#about"
weight = 2
[[menu.main]]
name = "Visi Misi"
url = "#service"
weight = 3
[[menu.main]]
name = "Galeri"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Informasi"
url = "#blog"
weight = 5
[[menu.main]]
name = ""
url = "#"
weight = 6
[[menu.sitemap]]
name = "Tentang"
url = "https://garisfajarnusantaraabadi.com/#about"
weight = 1
[[menu.sitemap]]
name = "Pinned Information"
url = "https://garisfajarnusantaraabadi.com/#service"
weight = 2
[[menu.sitemap]]
name = "Galeri"
url = "https://garisfajarnusantaraabadi.com/#portfolio"
weight = 3
[[menu.sitemap]]
name = "Informasi"
url = "https://garisfajarnusantaraabadi.com#blog"
weight = 4
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All rights reserved © Biro Puskominfo GFN 2023"
footerLogo = "images/my-image/SMAIA-LOGO.png"
formspreeURL = "https://formspree.io/f/meqvzkwn"
googleAnalytics = "G-KES8R3D2NC"
logo = "images/my-image/SMAIA-LOGO.png"
[params.address]
address = "Jakarta"
email = "mail@garisfajarnusantaraabadi.com"
openingHours = "24 Hours"
phone = ""
[params.map]
APIkey = "AIzaSyCpD25r44kI5riInNf9AOGWNpAVGziO9Iw"
latitude = "-6.31965338630833"
longitude = "106.87723546604138"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-whatsapp"
url = "https://wa.me/6281310729415"
weight = 1
[[params.social]]
icon = "fa-instagram"
url = "https://instagram.com/"
weight = 2
[[params.social]]
icon = "fa-youtube"
url = "https://youtube.com"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
